# new town / new weather
- env_id: LeaderBoard-v0
  env_configs:
    carla_map: Town01
    routes_group: null
    weather_group: train
- env_id: LeaderBoard-v0
  env_configs:
    carla_map: Town06
    routes_group: null
    weather_group: train