TAG: 'mile'
LOG_DIR: 'tensorboard_logs'

GPUS: 2
BATCHSIZE: 1
STEPS: 50000
LIMIT_VAL_BATCHES: 0.05
N_WORKERS: 2
VAL_CHECK_INTERVAL: 20000

OPTIMIZER:
  ACCUMULATE_GRAD_BATCHES: 2

RECEPTIVE_FIELD: 6
FUTURE_HORIZON: 6

PRETRAINED:
  PATH: ''

DATASET:
  DATAROOT: ''
  VERSION: 'mini'