TAG: 'mile'
LOG_DIR: 'tensorboard_logs'

GPUS: 2
BATCHSIZE: 2
STEPS: 200000
LIMIT_TRAIN_BATCHES: 0.125
LIMIT_VAL_BATCHES: 0.125
N_WORKERS: 1
VAL_CHECK_INTERVAL: 10000

OPTIMIZER:
  ACCUMULATE_GRAD_BATCHES: 2

RECEPTIVE_FIELD: 6
FUTURE_HORIZON: 6

PRETRAINED:
  PATH: ''

DATASET:
  DATAROOT: ''
  VERSION: 'trainval'