defaults:
  - test_suites: pave_demo
  - agent: mile
  - _self_

carla_sh_path: ''
port: 2000

log_level: INFO
host: localhost
seed: 2021
no_rendering: false
kill_running: true
resume: true
log_video: true
show_debug: false

# PAVE control parameters
verbose: false
comodel: '127.0.0.1'
domain: 'AF_UNIX'
res: '1280x720'
tm-port: 8000
filter: 'vehicle.*'
gamma: 2.2
use_ekf: false
show_way: false

# End of PAVE control parameters

actors:
  hero:
    agent: mile
    reward:
      entry_point: reward.valeo_action:ValeoAction
    terminal:
      entry_point: terminal.leaderboard:Leaderboard
